name: unit-test-net-action

inputs:
  path:
    required: true
    type: string
  project_name:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Run Unit Test
      working-directory: ${{ inputs.path }}
      run: |
        dotnet restore ${{ inputs.project_name }}.sln
        dotnet build ${{ inputs.project_name }}.sln
        dotnet test ${{ inputs.project_name }}.Test/${{ inputs.project_name }}.Test.csproj --no-restore --verbosity normal
      shell: bash
