name: workflow-net
on: 
  workflow_dispatch:
  push:
      branches:
        - develop
      paths:
        - 'SmtpServerWinForms-main/**'

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

#Se debe configurar todos los frameworks para poder hacer las compilaciones
      - name: Configurar el entorno
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1'

