name: .NET Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.1.x'

    - name: Restore dependencies
      run: dotnet restore SmtpServerWinForms-main/SmtpServerWinForms.sln

    - name: Build
      run: dotnet build SmtpServerWinForms-main/SmtpServerWinForms.sln --configuration Release
