name: .NET Framework Build

on: [push]

jobs:
  build:
    runs-on: windows-latest  # Specifies the runner that the job will run on

    steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3

    - name: setup-msbuild              
      uses: microsoft/setup-msbuild@v2  
    
    - name: Checkout code
      uses: actions/checkout@v3
      

    - name: Setup NuGet CLI
      uses: NuGet/setup-nuget@v1

    - name: Restore dependencies with NuGet
      run: nuget restore SmtpServerWinForms-main/SmtpServerWinForms.sln

    - name: Build
      run: dotnet build SmtpServerWinForms-main/SmtpServerWinForms.sln  /p:platform="Any CPU" /p:configuration="Release"
    
    
    - name: Run tests
      run: dotnet test SmtpServerWinForms-main/SmtpServerWinForms.sln --configuration Release
