name: .NET Framework Build

on: [push]

jobs:
  build:
    runs-on: windows-latest  # Specifies the runner that the job will run on

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup NuGet CLI
      uses: NuGet/setup-nuget@v1

    - name: Restore dependencies with NuGet
      run: nuget restore SmtpServerWinForms-main/SmtpServerWinForms.sln

    - name: Verify DLL existence
      run: |
        if (Test-Path "SmtpServerWinForms-main/packages/BouncyCastle.Cryptography.2.4.0/lib/net461/BouncyCastle.Cryptography.dll") {
          Write-Host "BouncyCastle.Cryptography.dll exists"
        } else {
          Write-Host "BouncyCastle.Cryptography.dll does not exist"
          exit 1
        }
        if (Test-Path "SmtpServerWinForms-main/packages/MailKit.4.7.1.1/lib/net47/MailKit.dll") {
          Write-Host "MailKit.dll exists"
        } else {
          Write-Host "MailKit.dll does not exist"
          exit 1
        }
        # Añade más verificaciones para las otras dependencias si es necesario

    - name: Build
      run: dotnet build SmtpServerWinForms-main/SmtpServerWinForms.sln --configuration Release --platform x64
    
    - name: Run tests
      run: dotnet test SmtpServerWinForms-main/SmtpServerWinForms.sln --configuration Release
