name: .NET Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # Aquí puedes ajustar la versión que necesites

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release
